In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = np.array([
    [5, 3, 1500, 4, 2],
    [10, 2, 1200, 3, 1],
    [3, 4, 1800, 5, 2],
    [8, 3, 1300, 4, 2],
    [15, 2, 900, 2, 0],
    [7, 3, 1400, 3, 1],
    [2, 5, 2000, 6, 2],
    [6, 2, 1100, 3, 0],
    [12, 3, 1600, 4, 2],
    [4, 4, 1700, 5, 1]
])

In [ ]:
x = dataset[:,0:4]
print(x)

[[   5    3 1500    4]
 [  10    2 1200    3]
 [   3    4 1800    5]
 [   8    3 1300    4]
 [  15    2  900    2]
 [   7    3 1400    3]
 [   2    5 2000    6]
 [   6    2 1100    3]
 [  12    3 1600    4]
 [   4    4 1700    5]]


In [ ]:
y=dataset[:,4]
print(y)

[2 1 2 2 0 1 2 0 2 1]


In [ ]:
x_test=np.asarray([4,3,1505,5])

# Step-1: Calculate distance

In [ ]:
x

array([[   5,    3, 1500,    4],
       [  10,    2, 1200,    3],
       [   3,    4, 1800,    5],
       [   8,    3, 1300,    4],
       [  15,    2,  900,    2],
       [   7,    3, 1400,    3],
       [   2,    5, 2000,    6],
       [   6,    2, 1100,    3],
       [  12,    3, 1600,    4],
       [   4,    4, 1700,    5]])

In [ ]:
def eucledianDistance(x1,x2):
    sum = 0.0
    for a,b in zip(x1,x2):
      #print(a,b)
      sum += (a-b)**2
    return sum**0.5

In [ ]:
distances=[]
for i in x:
    distance = eucledianDistance(i,x_test)
    distances.append(distance)

distances=np.asarray(distances)

In [ ]:
print(distances)

[  5.19615242 305.06720571 295.00338981 205.04145922 605.10825478
 105.06188652 495.00909083 405.01111096  95.34149149 195.00256409]


# Step-2: Sort distances in ascending order

In [ ]:
distanceIndices = np.argsort(distances)
print(distanceIndices)

[0 8 5 9 3 2 1 7 6 4]


# Step-3: Select k neighbors

In [ ]:
k=7

distanceIndices = distanceIndices[:k]
distanceIndices

array([0, 8, 5, 9, 3, 2, 1])

# Step-4: Calculate majority

In [ ]:
label = dict()
label[0]=0
label[1]=0
label[2]=0

In [ ]:
for i in distanceIndices:
    result=y[i]
    print(result)
    label[result]=label[result]+1

2
2
1
1
2
2
1


In [ ]:
max(zip(label.values(),label.keys()))[1]

2