In [23]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [30]:
X, y = make_classification(n_samples=1000, n_features=20, n_informative=5, n_redundant=10, random_state=42)

In [31]:
model = DecisionTreeClassifier()

### Perform K-Fold cross validation

In [32]:
kf = KFold(n_splits=5, random_state=42, shuffle=True)
kf_scores = cross_val_score(model, X, y, cv=kf)
kf_scores

array([0.885, 0.895, 0.91 , 0.875, 0.955])

In [33]:
print(kf_scores.mean())

0.9039999999999999


### Perform Stratified K-Fold cross validation

In [34]:
skf = StratifiedKFold(n_splits=5, random_state=42, shuffle=True)
skf_scores = cross_val_score(model, X, y, cv=skf)
skf_scores

array([0.925, 0.925, 0.9  , 0.915, 0.89 ])

In [35]:
print(skf_scores.mean())

0.9109999999999999


### Using XGBoost

In [ ]:
import xgboost as xgb
xg = xgb.XGBClassifier(use_label_encoder = False, eval_metrics = 'logless')

In [38]:
kf = KFold(n_splits=5, random_state=42, shuffle=True)
kf_scores = cross_val_score(xg, X, y, cv=kf)
kf_scores

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\training.py:183: UserWarning: [19:51:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "eval_metrics", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\training.py:183: UserWarning: [19:51:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "eval_metrics", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\training.py:183: UserWarning: [19:51:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "eval_metrics", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\training.py:18

array([0.945, 0.94 , 0.935, 0.935, 0.95 ])