In [1]:
import numpy as np

In [2]:
data = [[2, 10], [2, 5], [8, 4], [5, 8], [7, 5], [6, 4], [1, 2], [4, 9]]
data = np.array(data)
data

array([[ 2, 10],
       [ 2,  5],
       [ 8,  4],
       [ 5,  8],
       [ 7,  5],
       [ 6,  4],
       [ 1,  2],
       [ 4,  9]])

In [6]:
# choose 3 random elements
random_indices = np.random.choice(data.shape[0], 3, replace=False)
print(random_indices)

print(data[random_indices])

[3 0 4]
[[ 5  8]
 [ 2 10]
 [ 7  5]]


In [7]:
a = [
     [1, 4],
     [3, 5]
]
a = np.array(a)
print(a[0,1])
print(a[:,1])

4
[4 5]
