# Introduction to python
We will cover from the basics to built-in libraries like Numpy and Pandas in Python.

## Basics

*   comments
*   datatype and variables
*   operator
*   conditional statements
*   loop
*   function



In [1]:
print('Hello World')

Hello World


In [2]:
print("AI Lab")

AI Lab


In [ ]:
# This is comment
# This is another comment

In [ ]:
"""
This is our second
AI Lab for fall 2024.


"""

'\nThis is our second\nAI Lab for fall 2024.\n\n\n'

In [ ]:
message = 'This is comments'
name = "Rahad Khan"
email = '''Dear sir,
        I hope you are doing well.'''

### Variable and Datatype

In [ ]:
student_ID = 164071
name = "Md Rahad Khan"
CGPA = 3.15
is_publication = True
a = 3+2j
b = 3-2j
print(student_ID)
print(name)
print(CGPA)
print(is_publication)
print(a*b)

164071
Md Rahad Khan
3.15
True
(13+0j)


In [ ]:
print(f'Student ID: {student_ID} name:{name}')
print(f'Name: {name}')
print(f'CGPA: {CGPA}')
print(f'Publication: {is_publication}')
print(f'Complex Number: {comp}')

Student ID: 164071 name:Md Rahad Khan
Name: Md Rahad Khan
CGPA: 3.15
Publication: True
Complex Number: (3+2j)


In [ ]:
message = '''Dear Sir,
Assalamu alaikum. I hope this mail find you well.'''
print(message)

Dear Sir,
Assalamu alaikum. I hope this mail find you well.


In [ ]:
print(type(student_ID))
print(type(name))
print(type(CGPA))
print(type(is_publication))
print(type(comp))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'bool'>
<class 'complex'>


In [ ]:
print(a.conjugate())
print(a.real)

(3-2j)
3.0


### String Operation

In [ ]:
message = "dhakA is Our CApiTal akA"    # [start:stop:step]
print(message[0])
print(message[2:5])#slice
print(message[2::3])#slice
print(message[0:])
print(message[:7])
print(message[3:-1])
print(message[::-1])

d
a  rAT A
dhakA is Our CApiTal akA
dhakA i
kA is Our CApiTal ak
Aka laTipAC ruO si Akahd


In [ ]:
print(message.capitalize())
print(message.upper())
print(message.find('akA'))
print(message.replace('akA','aBaa'))
print(message.count('akA'))

Dhaka is our capital aka
DHAKA IS OUR CAPITAL AKA
13
dhaBaa is Our CApiTal aBaa
2


In [ ]:
a = int(input('Enter your number:'))
b = int(input('Enter your number:'))

Enter your number:3
Enter your number:2


In [ ]:
print(f'Add: {a+b}')
print(f'Sub: {a-b}')
print(f'Product: {a*b}')
print(f'div: {a/b}')
print(f'div: {a//b}')
print(f'exp: {a**b}')

Add: 5
Sub: 1
Product: 6
div: 1.5
div: 1
exp: 9


###Task-1 Find reverse of a three digit number only using arithmetic operator

In [ ]:
num = int(input("Enter a number: "))


Enter a number: 534


In [ ]:
num//10

4

In [ ]:
rev = 0
rev = rev*10+num%10 # rev = 4
num = num//10 #53
rev = rev*10+num%10 # rev = 40 + 3 = 43
num = num//10 #5
rev = rev*10+num%10 # rev = 43*10 + 5 = 435
num = num//10 # 0
print(rev)

435


###Conditional Statement

In [ ]:
gender = 'm'
if gender=='f' or gender=='F':
  print('Welcome to our beauty parlour.')
  print('Bye')
elif gender=='m' or gender=='M':
  print('You have to wait a thousand year.')
else:
  print("You are not allow here....")
print('Exit')

You have to wait a thousand year.
Exit


In [ ]:
if 'aka' in message:
  print('Found')
else:
  print('Not Found')

Not Found


###Loop

In [ ]:
for i in range(1,10,2): #range(start,finish,update)
  print(i)

1
3
5
7
9


In [ ]:
# 0,-2,4,-6,........
sign = 1
for i in range(0,20,2):
  print(i*sign)
  sign = sign*-1

0
-2
4
-6
8
-10
12
-14
16
-18


In [ ]:
print('*'*4)

****


In [ ]:
for i in range(1,5):
  print('*'*i)

*
**
***
****


In [ ]:
for i in range(1,5):
  print('*'*i)

*
**
***
****


In [ ]:
for i in range(1,5):
  print(' '*(5-i)+'* '*i)

    * 
   * * 
  * * * 
 * * * * 


In [ ]:
num = int(input("Enter a number:"))

Enter a number:123456


In [ ]:
rev = 0
while num!=0:
  rev = rev*10+num%10
  num = num//10
print(rev)

654321


###Function

In [ ]:
# def fn_name(parameter):
#   function_body

def sum(a, b):
  c = a+b
  return c

In [ ]:
print(sum(10,20))
print(sum(3.5,6.75))
print(sum("Rahad"," Khan"))

30
10.25
Rahad Khan


In [ ]:
def hello(name):
  name = name.capitalize()
  print(f'Hello ',name)

hello('rashed')

Hello Rashed


In [ ]:
def test(arr):
  return (arr+arr)
print(test([1,2,3,4,5]))
print(test(100))
print(test("good"))

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
200
goodgood


In [ ]:
def minmax(arr):
  return min(arr),max(arr)
min_, max_ = minmax([1,0,9,8,-1])
print(f'min:{min_}, max:{max_}')

a = minmax([1,0,9,8,-1])
print(a[0],a[1])

min:-1, max:9
-1 9


In [ ]:
def canvote(is_citizen, age=0,is_passport=False):
    if not is_citizen:
        print("can't vote", age)
        return False
    if age >= 18:
        print("can vote at the age", age)
        return True
    else:
        print("can't vote at the age", age)
        return False

print(canvote(True, 132), '\n')
print(canvote(False), '\n')
#print(canvote(), '\n') # error: missing 1 argument
print(canvote(False, age = 31), '\n') # error: positional argument follows keyword argument

can vote at the age 132
True 

can't vote 0
False 

can't vote 31
False 



## Built-in data structure


1.   Tuple
2.   List
3.   Set
4.   Dictionary



### Tuple

In [ ]:
tuple1 = ('Red', 1, True, 'Yellow', 4.5,'Yellow')
print(tuple1)
print(len(tuple1))
print(tuple1[2])

print(tuple1)

('Red', 1, True, 'Yellow', 4.5, 'Yellow')
6
True
('Red', 1, True, 'Yellow', 4.5, 'Yellow')


In [ ]:
if 'red' in tuple1:
  print('found')
else:
  print('Not found')

Not found


In [ ]:
# We can't insert or delete item in a tuple
# Rather we can concate two tuple
# convert to list then add
tuple2 = ("Green",'Magenta')
tuple1 += tuple2
print(tuple1)
print(tuple2)

('red', 1, True, 'Yellow', 4.5, 'Yellow', 'Green', 'Magenta')
('Green', 'Magenta')


In [ ]:
x = list(tuple1)
x.append('cyan')
tuple1 = tuple(x)
print(tuple1)

('red', 1, True, 'Yellow', 4.5, 'Yellow', 'Green', 'Magenta', 'cyan')


In [ ]:
thisTuple = (1,"apple",True,[1,2],('SPL','AI'))
x, *y = thisTuple #unpack
print(x,y)

1 ['apple', True, [1, 2], ('SPL', 'AI')]


In [ ]:
x, y,c,d,e = thisTuple
print(x,y)

1 apple


In [ ]:
*x,y,z = thisTuple
print(x,y,z)

[1, 'apple', True] [1, 2] ('SPL', 'AI')


In [ ]:
x,*_,y = thisTuple  # ignore *_
print(x,y)

1 ('SPL', 'AI')


In [ ]:
for item in thisTuple:
  print(item)

1
apple
True
[1, 2]
('SPL', 'AI')


In [ ]:
for idx in range(len(thisTuple)):
  print(thisTuple[idx])

1
apple
True
[1, 2]
('SPL', 'AI')


### List

In [ ]:
arr = ['apple', 'grape', 100, 3.4,[1,2],(2,3)]
print(arr)
print(arr[:2])

['apple', 'grape', 100, 3.4, [1, 2], (2, 3)]
['apple', 'grape']


In [ ]:
print(arr[2:-1])

[100, 3.4, [1, 2]]


In [ ]:
arr.append([4,3,5])
print(arr)

['apple', 'grape', 100, 3.4, [1, 2], (2, 3), [4, 3, 5]]


In [ ]:
arr.insert(1,560)
print(arr)

['apple', 560, 'grape', 100, 3.4, [1, 2], (2, 3), [4, 3, 5]]


In [ ]:
print(arr.pop())
print(arr)

[4, 3, 5]
['apple', 560, 'grape', 100, 3.4, [1, 2], (2, 3)]


In [ ]:
print(arr.remove(100))
print(arr)

None
['apple', 560, 'grape', 3.4, [1, 2], (2, 3)]


In [ ]:
if 'apple' in arr:
  print('found')
else:
  print('Not found')

found


In [ ]:
print(len(arr))

6


In [ ]:
for item in arr:
  print(item)

apple
560
grape
3.4
[1, 2]
(2, 3)


In [ ]:
for i in range(len(arr)):
  print(arr[i])

apple
560
grape
3.4
[1, 2]
(2, 3)


In [ ]:
temp = [1,2,3,4,5]
print(temp*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
arr2 = temp
arr2.append(6)
print(temp,arr2)

[1, 2, 3, 4, 5, 6] [1, 2, 3, 4, 5, 6]


In [ ]:
arr2 = temp.copy()
arr2.append(7)
print(temp,arr2)

[1, 2, 3, 4, 5, 6] [1, 2, 3, 4, 5, 6, 7]


In [ ]:
foo = [1, 2, []]
bar = foo
bar[-1].append(4)
print(foo, bar, '\n')

foo = [1, 2, []]
bar = foo.copy()
bar[-1].append(5)
print(foo, bar, '\n')

import copy
foo = [1, 2, []]
bar = copy.deepcopy(foo)
bar[-1].append(5)
print(foo, bar, '\n')

[1, 2, [4]] [1, 2, [4]] 

[1, 2, [5]] [1, 2, [5]] 

[1, 2, []] [1, 2, [5]] 



### Set


In [ ]:
set1 = {"apple","banana",1,"apple"}
print(set1)

{1, 'banana', 'apple'}


In [ ]:
set2 = {True}
print(set2)

{True}


In [ ]:
set1 = {"apple","banana","apple",1,True}
print(set1)

{1, 'banana', 'apple'}


In [ ]:
set1.add("mango")
print(set1)

{1, 'banana', 'apple', 'mango'}


In [ ]:
set2 = {"yellow",'banana'}
set1.update(set2)
print(set1)

{1, 'mango', 'apple', 'banana', 'yellow'}


In [ ]:
set1.remove("yellow")
print(set1)

{1, 'mango', 'apple', 'banana'}


In [ ]:
# set can't access by index
for x in set1:
  print(x)

1
mango
apple
banana


### Dictionary

In [ ]:
person = {
    "name" : "Rahad Khan",
    "email" : "rahad@cse.uiu.ac.bd",
    "joined" : 2022,
    "course" : ["SPL","AI","DSA"]
}

In [ ]:
print(person)
print(person.keys())
print(person.values())

{'name': 'Rahad Khan', 'email': 'rahad@cse.uiu.ac.bd', 'joined': 2022, 'course': ['SPL', 'AI', 'DSA']}
dict_keys(['name', 'email', 'joined', 'course'])
dict_values(['Rahad Khan', 'rahad@cse.uiu.ac.bd', 2022, ['SPL', 'AI', 'DSA']])


In [ ]:
print(person.get('joined')) #get(key)
print(person['joined']) # We will use this approach often
print("name" in person)

2022
2022
True


In [ ]:
for key in person:# We will use this approach often.
  print(key,"--->",person[key])

name ---> Rahad Khan
email ---> rahad@cse.uiu.ac.bd
joined ---> 2022
course ---> ['SPL', 'AI', 'DSA']


In [ ]:
print(person.pop('course'))
print(person)

person['course'] = ["OOP","AOOP"]
print(person)

['SPL', 'AI', 'DSA']
{'name': 'Rahad Khan', 'email': 'rahad@cse.uiu.ac.bd', 'joined': 2022}
{'name': 'Rahad Khan', 'email': 'rahad@cse.uiu.ac.bd', 'joined': 2022, 'course': ['OOP', 'AOOP']}


### write a code that counts the frequency of each letter in a sentence

In [ ]:
graph = {
    "A" :["B","C","D"],
    "B" :["A","C","D"],
    "C" :["A","B","E"],
    "D" :["A","B","E"],
    "E" :["C","D"]
    }

In [ ]:
for vertex in graph:
  print(vertex,"->",graph[vertex])

A -> ['B', 'C', 'D']
B -> ['A', 'C', 'D']
C -> ['A', 'B', 'E']
D -> ['A', 'B', 'E']
E -> ['C', 'D']


## Class in python

In [ ]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def __str__(self):
    return f"Name: {self.name} and his/her age is:{self.age}"

p1 = Person("John", 36)

print(p1)

Name: John and his/her age is:36


In [ ]:
class Employee:
  emp_num = 0 # works like static variable common to all objects of a class

  def __init__(self, first, last, pay): # constructor
    self.first = first # member variable
    self.last = last # member variable
    self.email = first + '.' + last + '@email.com' # member variable
    self.pay = pay # member variable
    apple = 1 # not member variable
    Employee.emp_num += 1 # static variable

  def fullname(self): # self is comparable to this keyword of Java
    return f'{self.first} {self.last}'# "%s %s", self.first, self.last

  def applyRaise(self, raise_):
    self.pay = int(self.pay * raise_)

  def __str__(self): # toString()
    return f'{self.fullname()} - {self.email}: {self.pay}'

  @staticmethod # (Decorator) same working procedure for all objects of a class
  def is_holiday(day):
    holidays = [1, 30, 49, 350]
    if day in holidays:
        return True
    else:
      return False


In [ ]:
print(Employee.emp_num) # 0

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)


print(Employee.emp_num) # 2

print(emp_1.fullname()) # Corey Schafer

emp_1.applyRaise(1.5)
print(emp_1.pay) # 75000

print(Employee.is_holiday(30)) # True
print(Employee.is_holiday(31)) # False

print(emp_1) # Corey Schafer corey.schafer@gmail.com 75000

0
2
Corey Schafer
75000
True
False
Corey Schafer - Corey.Schafer@email.com: 75000


In [ ]:
class Developer(Employee):
    def __init__(self, first, last, pay, prog_lang):
        super().__init__(first, last, pay) # call parent class constructor
        self.prog_lang = prog_lang


class Manager(Employee):
  def __init__(self, first, last, pay, employees=None):
      super().__init__(first, last, pay)
      if employees is None:
          self.employees = []
      else:
          self.employees = employees

  def add_emp(self, emp):
      if emp not in self.employees:
          self.employees.append(emp)

  def remove_emp(self, emp):
      if emp in self.employees:
          self.employees.remove(emp)

  def print_emps(self):
      for emp in self.employees:
          print('-->', emp.fullname())


In [ ]:
dev_1 = Developer('Corey', 'Schafer', 50000, 'Python')
dev_2 = Developer('Test', 'Employee', 60000, 'Java')

mgr_1 = Manager('Sue', 'Smith', 90000, [dev_1])
print(mgr_1.email)

mgr_1.add_emp(dev_2)
mgr_1.print_emps()
print()

mgr_1.remove_emp(dev_2)
mgr_1.print_emps()
print()

print(isinstance(mgr_1, Manager))  # Is mgr_1 an instance of Manager?
print(isinstance(mgr_1, Employee))
print(isinstance(mgr_1, Developer))
print()

print(issubclass(Developer, Employee)) # Is Developer class a subclass of Employee class??

Sue.Smith@email.com
--> Corey Schafer
--> Test Employee

--> Corey Schafer

True
True
False

True


### write a class Point to store the x,y coords of 2D points.
1. The class should have the methods move_left, move_right, move_up, move down.
2. move_left moves the point 1 cell to the left, move_right moves the point 1 cell to the right
3. move_up moves the point 1 cell up, and move_down moves the point 1 cell down
4. write a distance function to calculate the manhattan distance between two points

In [ ]:

class Point:

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def move_left(self):
        self.x -= 1

    def move_right(self):
        self.x += 1

    def move_up(self):
        self.y += 1

    def move_down(self):
        self.y -= 1

    def __str__(self):
        return f"Point({self.x}, {self.y})"

    @staticmethod
    def manhattan_distance(p1, p2):
        return abs(p1.x - p2.x) + abs(p1.y - p2.y)


if __name__ == "__main__":
    point1 = Point(2, 3)
    point2 = Point(5, 1)

    print(f"Initial positions: {point1}, {point2}")
    point1.move_left()
    point1.move_up()
    print(f"Point1 after movements: {point1}")

    distance = Point.manhattan_distance(point1, point2)
    print(f"Manhattan distance between {point1} and {point2}: {distance}")


Initial positions: Point(2, 3), Point(5, 1)
Point1 after movements: Point(1, 4)
Manhattan distance between Point(1, 4) and Point(5, 1): 7


## Numpy


In [2]:
# numpy tutorial - http://cs231n.github.io/python-numpy-tutorial/#numpy-arrays
# numpy uses the facility of GPU. So, try to use it instead of for loop
import numpy as np

In [ ]:
a = [3, 6, 7]
print(type(a))
arr = np.array(a)
print(type(arr))



<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
book_list = [['ics','dm','dld', 'dsa'],['c','java','python', 'c++']]
book_arr = np.array(book_list)
print(book_arr.shape[1])

4


In [3]:
a = [
     [1, 4],
     [3, 5]
]
a = np.array(a)
print(a.shape)

(2, 2)


In [7]:
print(a[0,1])
print(a[:,1])

4
[4 5]


In [ ]:
a = np.random.random((4, 5))
print(a)
a = np.random.randint(20, 200, (4, 5))
#a = np.random.randint(low=0, high=10, size=(4, 5))
print(a)

[[0.24368885 0.8065591  0.50695374 0.61552625 0.25738599]
 [0.66203892 0.24291312 0.95529404 0.69414786 0.12850207]
 [0.42976043 0.95845318 0.11812095 0.90742943 0.49568878]
 [0.85667183 0.15440964 0.5345324  0.76600628 0.73507528]]
[[ 36  38 140 186 195]
 [128 161  21  54 193]
 [ 97 129  42  27 120]
 [ 57 193 111 102 129]]


In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(3)# Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y)
print(np.add(x, y)) #time complexity O(1) if we use GPU

print( x+100 )
print((x+100) / 2)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[101 102]
 [103 104]]
[[50.5 51. ]
 [51.5 52. ]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z= x/y
print(z)
z = x*y # element wise multiplication
print(z)


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5 12]
 [21 32]]


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[3,1],
              [0,-1],
              [5,2]])
z = np.dot(a,b)
#z = a.dot(b)
print(z)

[[18  5]
 [42 11]]


In [ ]:
x = np.array([
              [1,2,5],
              [3,4,1]
              ])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[8 8]"

16
[4 6 6]
[8 8]


In [ ]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
#print(v * w) # can't do this, need to reshape
v = np.reshape(v, (3, 1))
print(v)
print(v.shape)
print(w.shape)

print(v * w)

[[1]
 [2]
 [3]]
(3, 1)
(2,)
[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
a = np.array([[1,2,3,4],
              [1,0,-1,5],
              [4,5,6,6]])
print(a.shape)
b = np.reshape(a,(2,3,2))
print(b)

(3, 4)
[[[ 1  2]
  [ 3  4]
  [ 1  0]]

 [[-1  5]
  [ 4  5]
  [ 6  6]]]


In [ ]:
a = np.array([[2,5],[6,3]])
b = np.array([[1,3],
             [2,4],
             [6,7]])
z = np.dot(a,b.T)
print(z)

[[17 24 47]
 [15 24 57]]


## Pandas

In [ ]:
import pandas as pd

### Load dataset
1. load dataset using pandas
2. get infomation about data, columns, and statistics

In [ ]:
PATH = '/content/drive/MyDrive/Research/Dataset/ET_result.csv'

In [ ]:
df = pd.read_csv(PATH)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Research/Dataset/ET_result.csv'

In [ ]:
#To display all column and row
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.columns

In [ ]:
df = df.drop('Unnamed: 0',axis=1)

In [ ]:
df.info()

In [ ]:
df.describe()